package modelo;
// Generated 26-may-2016 13:02:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private int idUsuarioEmisor;
     private int idUsuarioReceptor;
     private int idProducto;
     private String mensaje;
     private Date fecha;
     private String hora;
     private int leido;

    public Mensaje() {
    }

    public Mensaje(int idUsuarioEmisor, int idUsuarioReceptor, int idProducto, String mensaje, Date fecha, String hora, int leido) {      
       this.idUsuarioEmisor = idUsuarioEmisor;
       this.idUsuarioReceptor = idUsuarioReceptor;
       this.idProducto = idProducto;
       this.mensaje = mensaje;
       this.fecha = fecha;
       this.hora = hora;
       this.leido = leido;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public int getIdUsuarioEmisor() {
        return this.idUsuarioEmisor;
    }
    
    public void setIdUsuarioEmisor(int idUsuarioEmisor) {
        this.idUsuarioEmisor = idUsuarioEmisor;
    }
    public int getIdUsuarioReceptor() {
        return this.idUsuarioReceptor;
    }
    
    public void setIdUsuarioReceptor(int idUsuarioReceptor) {
        this.idUsuarioReceptor = idUsuarioReceptor;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public int getLeido() {
        return this.leido;
    }
    
    public void setLeido(int leido) {
        this.leido = leido;
    }




}


