package modelo;
// Generated 26-may-2016 13:02:19 by Hibernate Tools 4.3.1



/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer idSubCategoria;
     private String nombre;
     private String descripcion;
     private int activo;
     private int idCategoria;

    public Subcategoria() {
    }

    public Subcategoria(String nombre, String descripcion, int activo, int idCategoria) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.activo = activo;
       this.idCategoria = idCategoria;
    }
   
    public Integer getIdSubCategoria() {
        return this.idSubCategoria;
    }
    
    public void setIdSubCategoria(Integer idSubCategoria) {
        this.idSubCategoria = idSubCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }




}


