package modelo;
// Generated 26-may-2016 13:02:19 by Hibernate Tools 4.3.1

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private int telefono1;
     private int telefono2;
     private String provincia;
     private String tipoUsuario;
     private String email;
     private String usuario;
     private String password;
     private int activo;

    public Usuario() {
    }

    public Usuario(String nombre, String apellido1, String apellido2, int telefono1, int telefono2, String provincia, String tipoUsuario, String email, String usuario, String password, int activo) {
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.provincia = provincia;
       this.tipoUsuario = tipoUsuario;
       this.email = email;
       this.usuario = usuario;
       this.password = password;
       this.activo = activo;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public int getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(int telefono1) {
        this.telefono1 = telefono1;
    }
    public int getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(int telefono2) {
        this.telefono2 = telefono2;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }




}


